<?php
header('Content-Type: application/json');
require_once 'db_connect.php';

if (session_status() === PHP_SESSION_NONE) session_start();
if (!isset($_SESSION['user_id'])) {
    sendJSONResponse(['success' => false, 'message' => 'Unauthorized'], 401);
}

$user_id = $_SESSION['user_id'];
$input = json_decode(file_get_contents('php://input'), true);
$subject = $input['subject'] ?? null;
$grade = $input['grade'] ?? null;
$academic_year = '2024/2025'; // Bisa diambil dari pengaturan global nanti

if (!$subject || !$grade) {
    sendJSONResponse(['success' => false, 'message' => 'Mata Pelajaran dan Kelas wajib diisi.'], 400);
}

// --- SIMULASI PANGGILAN AI ---
// Di dunia nyata, ini akan memanggil API Gemini.
// Untuk sekarang, kita gunakan data tiruan (mock data).
function getMockSyllabus($subject, $grade) {
    $subject_lower = strtolower($subject);

    if (strpos($subject_lower, 'fiqih') !== false) {
        return [
            'ganjil' => [
                'Memahami konsep Thaharah (bersuci) dari hadas dan najis.',
                'Menganalisis tata cara wudhu, tayamum, dan mandi wajib.',
                'Mempraktikkan shalat fardhu lima waktu dengan benar.',
                'Memahami ketentuan puasa Ramadhan dan puasa sunnah.',
                'Menganalisis konsep zakat fitrah dan zakat maal.',
            ],
            'genap' => [
                'Memahami sejarah dan tata cara ibadah haji dan umrah.',
                'Menganalisis konsep jual beli yang sesuai syariat Islam.',
                'Memahami konsep riba dan bahayanya dalam transaksi ekonomi.',
                'Menganalisis ketentuan tentang makanan dan minuman yang halal dan haram.',
                'Memahami konsep pernikahan dan keluarga dalam Islam.',
            ]
        ];
    } elseif (strpos($subject_lower, 'ipa') !== false) {
        return [
            'ganjil' => [
                'Mengidentifikasi ciri-ciri makhluk hidup dan benda mati.',
                'Menganalisis ekosistem dan interaksi antar komponennya.',
                'Memahami konsep energi dan transformasinya dalam kehidupan sehari-hari.',
                'Mendeskripsikan sistem tata surya dan pergerakan benda langit.',
                'Melakukan percobaan sederhana tentang sifat-sifat zat (padat, cair, gas).',
            ],
            'genap' => [
                'Memahami sistem pernapasan pada manusia dan hewan.',
                'Menganalisis sistem peredaran darah dan fungsinya.',
                'Memahami konsep gaya dan gerak serta hukum Newton.',
                'Mendeskripsikan prinsip kerja pesawat sederhana.',
                'Memahami konsep listrik statis dan dinamis dalam rangkaian sederhana.',
            ]
        ];
    }

    // Respons default jika mapel tidak ditemukan
    return [
        'ganjil' => ["Tujuan Pembelajaran 1 untuk {$subject} (Ganjil) - Generated by AI."],
        'genap' => ["Tujuan Pembelajaran 1 untuk {$subject} (Genap) - Generated by AI."]
    ];
}

$syllabus = getMockSyllabus($subject, $grade);
// --- AKHIR SIMULASI AI ---

$pdo = getDBConnection();

try {
    $pdo->beginTransaction();

    // 1. Hapus semua Prota yang ada untuk mapel dan kelas ini
    $stmtDelete = $pdo->prepare("DELETE FROM annual_programs WHERE user_id = ? AND subject = ? AND grade = ? AND academic_year = ?");
    $stmtDelete->execute([$user_id, $subject, $grade, $academic_year]);

    // 2. Masukkan Prota baru dari hasil generate AI
    $stmtInsert = $pdo->prepare("INSERT INTO annual_programs (user_id, subject, grade, academic_year, semester, learning_objective) VALUES (?, ?, ?, ?, ?, ?)");
    foreach ($syllabus['ganjil'] as $objective) { $stmtInsert->execute([$user_id, $subject, $grade, $academic_year, 'Ganjil', $objective]); }
    foreach ($syllabus['genap'] as $objective) { $stmtInsert->execute([$user_id, $subject, $grade, $academic_year, 'Genap', $objective]); }

    $pdo->commit();
    sendJSONResponse(['success' => true, 'message' => 'Silabus berhasil di-generate dan disimpan!']);
} catch (Exception $e) {
    if ($pdo->inTransaction()) $pdo->rollBack();
    sendJSONResponse(['success' => false, 'message' => 'Database error: ' . $e->getMessage()], 500);
}
?>