<?php
header('Content-Type: application/json');
require_once 'db_connect.php'; // For sendJSONResponse function

if (session_status() === PHP_SESSION_NONE) session_start();
if (!isset($_SESSION['user_id'])) {
    sendJSONResponse(['success' => false, 'message' => 'Unauthorized'], 401);
}

$input = json_decode(file_get_contents('php://input'), true);
$subject = $input['subject'] ?? null;
$grade = $input['grade'] ?? null;

if (!$subject || !$grade) {
    sendJSONResponse(['success' => false, 'message' => 'Mata Pelajaran dan Kelas wajib diisi.'], 400);
}

// --- SIMULASI PANGGILAN AI GEMINI ---
// Di dunia nyata, ini akan memanggil API Gemini.
// Untuk sekarang, kita gunakan data tiruan (mock data).
function getMockPromesSyllabus($subject, $grade) {
    $subject_lower = strtolower($subject);

    if (strpos($subject_lower, 'fiqih') !== false) {
        return [
            'ganjil' => [
                'Memahami konsep Thaharah (bersuci) dari hadas dan najis.',
                'Menganalisis tata cara wudhu, tayamum, dan mandi wajib.',
                'Mempraktikkan shalat fardhu lima waktu dengan benar.',
                'Memahami ketentuan puasa Ramadhan dan puasa sunnah.',
                'Menganalisis konsep zakat fitrah dan zakat maal.',
            ],
            'genap' => [
                'Memahami sejarah dan tata cara ibadah haji dan umrah.',
                'Menganalisis konsep jual beli yang sesuai syariat Islam.',
                'Memahami konsep riba dan bahayanya dalam transaksi ekonomi.',
                'Menganalisis ketentuan tentang makanan dan minuman yang halal dan haram.',
                'Memahami konsep pernikahan dan keluarga dalam Islam.',
            ]
        ];
    } elseif (strpos($subject_lower, 'ipa') !== false) {
        return [
            'ganjil' => [
                'Mengidentifikasi ciri-ciri makhluk hidup dan benda mati.',
                'Menganalisis ekosistem dan interaksi antar komponennya.',
                'Memahami konsep energi dan transformasinya dalam kehidupan sehari-hari.',
                'Mendeskripsikan sistem tata surya dan pergerakan benda langit.',
                'Melakukan percobaan sederhana tentang sifat-sifat zat (padat, cair, gas).',
            ],
            'genap' => [
                'Memahami sistem pernapasan pada manusia dan hewan.',
                'Menganalisis sistem peredaran darah dan fungsinya.',
                'Memahami konsep gaya dan gerak serta hukum Newton.',
                'Mendeskripsikan prinsip kerja pesawat sederhana.',
                'Memahami konsep listrik statis dan dinamis dalam rangkaian sederhana.',
            ]
        ];
    }

    // Respons default jika mapel tidak ditemukan
    return [
        'ganjil' => ["Tujuan Pembelajaran 1 untuk {$subject} Kelas {$grade} (Ganjil) - Generated by AI."],
        'genap' => ["Tujuan Pembelajaran 1 untuk {$subject} Kelas {$grade} (Genap) - Generated by AI."]
    ];
}

try {
    $syllabus = getMockPromesSyllabus($subject, $grade);
    sendJSONResponse(['success' => true, 'data' => $syllabus]);
} catch (Exception $e) {
    sendJSONResponse(['success' => false, 'message' => 'AI Error: ' . $e->getMessage()], 500);
}
?>