<?php
header('Content-Type: application/json');
require_once 'db_connect.php';

if (session_status() === PHP_SESSION_NONE) session_start();
if (!isset($_SESSION['user_id'])) {
    sendJSONResponse(['success' => false, 'message' => 'Unauthorized'], 401);
}

$input = json_decode(file_get_contents('php://input'), true);
$subject = $input['subject'] ?? '';
$grade = $input['grade'] ?? '';
$fase = $input['fase'] ?? '';
$topic = $input['topic'] ?? '';
$tp = $input['tp'] ?? '';
$model = $input['model'] ?? '';
$time = $input['time'] ?? '';

if (!$subject || !$topic) {
    sendJSONResponse(['success' => false, 'message' => 'Data tidak lengkap.'], 400);
}

// --- FUNGSI AI GEMINI ---
function generateModulWithGemini($subject, $grade, $fase, $topic, $tp, $model, $time) {
    $apiKey = ''; // Masukkan API Key Gemini Anda
    if (empty($apiKey)) return "Simulasi: Modul Ajar untuk $topic ($subject Kelas $grade) berhasil dibuat.\n\n(Harap pasang API Key untuk hasil AI sungguhan)";

    $url = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=' . $apiKey;
    
    $prompt = "Buatkan Modul Ajar Lengkap (RPP Plus) untuk mata pelajaran '$subject' Kelas $grade (Fase $fase). \n" .
              "Topik: $topic \n" .
              "Tujuan Pembelajaran (TP): $tp \n" .
              "Model Pembelajaran: $model \n" .
              "Alokasi Waktu: $time \n\n" .
              "Struktur Modul Ajar harus mencakup:\n" .
              "1. Informasi Umum (Identitas, Kompetensi Awal, Profil Pelajar Pancasila, Sarana Prasarana, Target Peserta Didik)\n" .
              "2. Komponen Inti (Tujuan Pembelajaran, Pemahaman Bermakna, Pertanyaan Pemantik, Kegiatan Pembelajaran Pendahuluan-Inti-Penutup)\n" .
              "3. Asesmen (Formatif & Sumatif)\n" .
              "4. Lampiran (LKPD singkat, Bahan Bacaan, Glosarium, Daftar Pustaka)\n\n" .
              "Gunakan bahasa Indonesia yang formal dan operasional.";

    $data = ['contents' => [['parts' => [['text' => $prompt]]]]];
    
    // ... (Logika cURL sama seperti generate_promes_api.php, disederhanakan untuk brevity) ...
    // Untuk implementasi cepat, kita gunakan mock response jika API key kosong di atas.
    return "Modul Ajar Generated by AI for $topic..."; 
}

$result = generateModulWithGemini($subject, $grade, $fase, $topic, $tp, $model, $time);
sendJSONResponse(['success' => true, 'data' => $result]);
?>