name: Deploy ke Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload File via FTP
    runs-on: ubuntu-latest
    steps:
      - name: Mengambil Kode Terbaru
        uses: actions/checkout@v4
        
      - name: Mengirim ke Hostinger (Proses Deploy)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Sesuaikan folder di bawah ini jika lokasi web SADIGS Bos bukan di public_html utama
          server-dir: /domains/sadigs.villaquranbaronmalang.com/public_html/
          danger-clean-delete: false